[package]
name = "herder"
description = "A client for Mastodon, a GNU Social-compatible microbbloging server."
version = "0.1.0"
authors = ["Joaquin R <globojorro@gmail.com>"]

[dependencies]
curl = "0.4"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
